version: "3"

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    network_mode: "host"
    volumes:
      - ./certs:/etc/nginx/certs
      - ./nginx.conf:/etc/nginx/nginx.conf
    restart: always

  redis:
    image: redis:7.2-alpine
    container_name: redis
    command: |
      redis-server --loglevel notice --port 6379
    network_mode: "host"
    volumes:
      - redis:/data
    restart: always

volumes:
  redis:
